

#create user


##Login with correct details
POST http://127.0.0.1:3000/auth/sign_in
Content-Type: application/json

{
	"email":"s90six@gmail.com",
	"password":"pword1"

}



POST http://127.0.0.1:3000/questions/ask
Content-Type: application/json

{
	
	
	"user_id":1,
	"category_id":1,
	"title":"From Post Man 2",
	"body":"This Came From Post Man"
	

}

